#!/bin/bash
#commit e push
#ex :  . "/workspaces/MirrorFashion/cpg" "/workspaces/MirrorFashion/cpg" "$(date)" "main"
#ex :  . "/workspaces/MirrorFashion/cpg" "." "$(date)" "main"
cpg () {

     add=${1};
     message=${2};
     branch=${3};

     git add ${add} ;
     git commit -m "${message}" ;
     git push -u origin "${branch}" ;
     git push ;
     git status ;
     git log ;

}

cpg "${1}" "${2}" "${3}"

up () {
     v=${1}
     for e in ${v[@]}
          do
               . "/workspaces/MirrorFashion/cpg" "${e}" "$(date)" "main"         
          done


      #t="../../../Filho2.txt ../../../Pai2.txt ../../../r0307.txt" ; up "${t}"
}