#!/bin/bash
#commit e push
#ex :  . "/workspace/MirrorFashion/cpg" "/workspace/MirrorFashion/cpg" "$(date)" "main"
#ex :  . "/workspace/MirrorFashion/cpg" "." "$(date)" "main"
cpg () {

     add=${1};
     message=${2};
     branch=${3};

     git add ${add} ;
     git commit -m "${message}" ;
     git push -u origin "${branch}" ;
     git push ;
     git status ;
     git log ;

}

cpg "${1}" "${2}" "${3}"

