#!/bin/bash

dalias () {
     alias a='ls -la' 
     alias c='clear' 
     alias cS='cd "/workspaces/MirrorFashion/src/Slide/componentsSlide"'
     alias cS2='export CS="/workspaces/MirrorFashion/src/Slide/componentsSlide" && export CSgtd="/workspaces/MirrorFashion/src/Slide/componentsSlide/gridTD"'
}

dalias

cS ;
cS2 ;
