#!/bin/bash

#-------------------------------------------------------------------------------------------------------------------------------

conthookjsFilho="/*#imports*/
import './css/gtd${2}fh${1}.css' 
import './css/gtd${2}fh${1}A.css'
import { gtf${1}_funções } from './f/gtfh${1}F.js'
import {
  Adicionar_class,
  Aumentar_ElementoPai,
  Diminuir_ElementoPai,
  gridTN,
  Analise_class
} from '../../../DBanner/f/f.js'
/*Imports#*/

/*#Hook*/
const  GridTD${2}F${1} = ({ Obj_Pai_Props }) => {

/*#Hook_Escopo*/
/*Hook_Escopo#*/

/*#Hook_Conteudo*/  
return (
    <div className='gridTD${1}_F${1} gridTD${1}F animation1_gridTD${1}F animation1_gridTD${1}_F${1}'
    /*onClick={gridTN.gridTN${1}.Disparar_Evento_Quando.Click}*/
    /*onMouseOut={gridTN.gridTN${1}.Disparar_Evento_Quando.Out}*/
    /*onMouseOver={gridTN.gridTN${1}.Disparar_Evento_Quando.Over}*/
    /*onDrag={gridTN.gridTN${1}.Disparar_Evento_Quando.Drag}*/
    /*onDrop={gridTN.gridTN${1}.Disparar_Evento_Quando.Drop}*/
    /*onDragStart={gridTN.gridTN${1}.Disparar_Evento_Quando.DragStart}*/
    /*onDragOver={gridTN.gridTN${1}.Disparar_Evento_Quando.DragOver} */>
            <div 
            className='gridTD${1}N${1}_1 gridTD${1}N${1}_g animation1_gridTD${1}N${1} animation1_gridTD${1}N${1}1'
            /*onClick={gridTN.gridTN${1}.Disparar_Evento_Quando.Click}*/
            /*onMouseOut={gridTN.gridTN${1}.Disparar_Evento_Quando.Out}*/
            /*onMouseOver={gridTN.gridTN${1}.Disparar_Evento_Quando.Over}*/
            /*onDrag={gridTN.gridTN${1}.Disparar_Evento_Quando.Drag}*/
            /*onDrop={gridTN.gridTN${1}.Disparar_Evento_Quando.Drop}*/
            /*onDragStart={gridTN.gridTN${1}.Disparar_Evento_Quando.DragStart}*/
            /*onDragOver={gridTN.gridTN${1}.Disparar_Evento_Quando.DragOver} */>
              gridTD${1}N${1}1 
            </div>
            <div className='gridTD${1}N${1}_2 gridTD${1}N${1}_g animation1_gridTD${1}N${1} animation1_gridTD${1}N${1}2'
            /*onClick={gridTN.gridTN${1}.Disparar_Evento_Quando.Click}*/
            /*onMouseOut={gridTN.gridTN${1}.Disparar_Evento_Quando.Out}*/
            /*onMouseOver={gridTN.gridTN${1}.Disparar_Evento_Quando.Over}*/
            /*onDrag={gridTN.gridTN${1}.Disparar_Evento_Quando.Drag}*/
            /*onDrop={gridTN.gridTN${1}.Disparar_Evento_Quando.Drop}*/
            /*onDragStart={gridTN.gridTN${1}.Disparar_Evento_Quando.DragStart}*/
            /*onDragOver={gridTN.gridTN${1}.Disparar_Evento_Quando.DragOver} */>
              gridTD${1}N${1}2
            </div>
            <div className='gridTD${1}N${1}_3 gridTD${1}N${1}_g animation1_gridTD${1}N${1} animation1_gridTD${1}N${1}3'
            /*onClick={gridTN.gridTN${1}.Disparar_Evento_Quando.Click}*/
            /*onMouseOut={gridTN.gridTN${1}.Disparar_Evento_Quando.Out}*/
            /*onMouseOver={gridTN.gridTN${1}.Disparar_Evento_Quando.Over}*/
            /*onDrag={gridTN.gridTN${1}.Disparar_Evento_Quando.Drag}*/
            /*onDrop={gridTN.gridTN${1}.Disparar_Evento_Quando.Drop}*/
            /*onDragStart={gridTN.gridTN${1}.Disparar_Evento_Quando.DragStart}*/
            /*onDragOver={gridTN.gridTN${1}.Disparar_Evento_Quando.DragOver} */>
              gridTD${1}N${1}3
          </div>
    </div>
    );
/*Hook_Conteudo#/  

}
/*Hook#*/

/*#Exports*/
export {  GridTD${2}F${1} }
/*Exports#*/
"  

#-------------------------------------------------------------------------------------------------------------------------------

contcssFilho="/*#CSS*/
/*#P1*/
.gridTD${1}_F${1} {
background-color:wheat;
grid-area:gridTD${1}F${1};
display:flex;
flex-direction:row;
overflow-x:scroll;
overflow-y:hidden;
height:250vh;
}
/*P1#*/

/*#P2*/
.gridTD${1}N${1}_g {
position:relative;
text-align:center;
font-size:3rem;
font-weight:500;
min-height:100%;
min-width:100%;
border-radius:25px;
}
/*P2#*/

/*#P3*/
.gridTD${1}N${1}_1 {
background-color:brown;
}
/*P3#*/

/*#P4*/ 
.gridTD${1}N${1}_2 {
background-color:tomato;
background-image:
linear-gradient(0deg,rgba(0,0,0,0.6),
rgba(0,0,0,0.2)40%,rgba(0,0,0,0.2)80%,
rgba(0,0,0,0.4)),
url(/workspace/MirrorFashion/public/images/pink-fur-fabulous-fashion.jpg);
background-repeat:no-repeat;
background-size:140%;
}
/*P4#*/

/*#P5*/
.gridTD${1}N${1}_3 {
background-color:darkblue;
background-image:
linear-gradient(0deg,rgba(0,0,0,0.6),
rgba(0,0,0,0.2)40%,rgba(0,0,0,0.2)80%,
rgba(0,0,0,0.4)),
url(/workspace/MirrorFashion/public/images/pink-fur-fabulous-fashion.jpg);
background-repeat:no-repeat;
background-size:140%;
}
/*P5#*/

/*CSS#*/
"

#-------------------------------------------------------------------------------------------------------------------------------

conthookjsFilhoF="/*#Comentários*/
  //Funções gtf${1}

  /*#Obj_Main*/  
  const gtf${1}_funções = {
    /*#f1*/
    teste : () => {
        console.log('Esse é o objeto que contém métodos do hook gtf${1}')
    }
  }

  /*#Export*/
  export { gtf${1}_funções }
  " 

#-------------------------------------------------------------------------------------------------------------------------------  

dir1="/workspace/MirrorFashion/src/Slide/componentsSlide/gridTD/${2}" ;

#${1} é o valor que irá variar
#${2} é o valor constante

CriarDir "gtd${2}f${1}" "${dir1}"
dir1="${dir}/gtd${2}f${1}";

CriarDirG "css f" "${dir1}"
dir2="${dir1}/css";
dir3="${dir1}/f";

arqFilhoJs="gtd${2}fh${1}.js";
arqFilhoCss="gtd${2}fh${1}.css";
arqFilhoCssA="gtd${2}fh${1}A.css"; 
arqFilhoFJs="gtfh${1}F.js";
 
dropCont "${conthookjsFilho}" "${arqFilhoJs}" "${dir1}" ;
dropCont "${contcssFilho}" "${arqFilhoCss}" "${dir2}" ;
dropCont "/*Animação do hook gtd${2}fh${1}*/" "${arqFilhoCssA}" "${dir2}" ;
dropCont "${conthookjsFilhoF}" "${arqFilhoFJs}" "${dir3}" ;

#-------------------------------------------------------------------------------------------------------------------------------
