#!bin/bash

#-------------------------------------------------------------------------------------------------------------------------------
conthookjsPai="/*#Comentários*/
// Este é o Hook GridTD${1}
/*Comentários#*/

/*#Imports*/

import './css/1.css';
import './css/gridTD.css';
import {
  Adicionar_class,
  Aumentar_ElementoPai,
  Diminuir_ElementoPai,
  gridTN,
} from '../../DBanner/f/f.js';
import { GridTD${1}F1 } from './gtd${1}f1/gtd${1}fh1';
import { GridTD${1}F2 } from './gtd${1}f2/gtd${1}fh2';
import { GridTD${1}F3 } from './gtd${1}f3/gtd${1}fh3';
import { GridTD${1}FB } from './gtd${1}fB/gtd${1}fhB.js'
import { HerençaOf_GridTD${1} } from './hgtd${1}/hgtd${1}.js';

/*Imports#*/

//Fase : Teste

/*#Hook*/

const GridTD${1} = () => {

  /*#EscopoGridTD${1}*/

  const 
  display_none = { display: 'none' },
  Herença = {HerençaOf_GridTD${1}} ;

  /*EscopoGridTD${1}#*/

  /*#HookCont${1}*/
  return (
    <div className='gridTD${1}'>
      <GridTD${1}FB Obj_Pai_Props={Herença}/>
      <GridTD${1}F1 Obj_Pai_Props={Herença}/>
      <GridTD${1}F2 Obj_Pai_Props={Herença}/>
      <GridTD${1}F3 Obj_Pai_Props={Herença}/>
    </div>
  );
  /*HookCont${1}#*/

};

/*Hook#*/

/*#Exports*/

export { GridTD${1} };

/*Exports#*/
"

#-------------------------------------------------------------------------------------------------------------------------------

contcssPai="
.gridTD${1} {
  position: absolute;
  display: grid;
  /*grid-template-columns: 3fr 1fr 1fr;*/
  grid-template-areas:
    '. . . . .'
    'gridTFB gridTFB gridTFB gridTFB gridTFB'
    '. . . . .'
    '. GridTF1' GridTF2 GridTF3 .'
    '. . . . .';

  min-height: 500vh;
  min-width: 90vw;
  width: 100vw;
  gap: 10px;
}

.gridTD${1}F {
  position: relative;
  display: grid;
  align-items: center;
  text-align: center;
  font-size: 3rem;
  font-weight: 500;
  box-shadow: 0px 0px 50px 50px black;
  background-color: black;
  overflow-x: hidden;
  overflow-y: hidden;
}

/*------------------------------------------------------------------------------------------------------------------------------------*/
"
#-------------------------------------------------------------------------------------------------------------------------------

conthookjsPaiObj="/*#Comentários*/
  //Funções GridTD${1}

  /*#Obj_Main*/  
  const HerençaOf_GridTD${1} = {
    /*#f1*/
    teste : () => {
        console.log('Esse é o objeto que contém métodos do hook GridTD${1} que serão herdados')
    }
  }

  /*#Export*/
  export { HerençaOf_GridTD${1} }
  " 

#-------------------------------------------------------------------------------------------------------------------------------

dir1="/workspace/MirrorFashion/src/Slide/componentsSlide/gridTD" ;

CriarDir "${1}" "${dir1}"
dir1="${dir}/${1}";

CriarDirG "css hgtd${1} f" "${dir1}"
dir2="${dir1}/css";

arqPaiJs="${1}.js";
arqPaiCss="${1}.css"; 
 
dropCont "${conthookjsPai}" "${arqPaiJs}" "${dir1}" ;
dropCont "${contcssPai}" "${arqPaiCss}" "${dir2}" ;

#-------------------------------------------------------------------------------------------------------------------------------

dir3="${dir1}/hgtd${1}" ;

arqPaiJsObj="hgtd${1}.js";
 
dropCont "${conthookjsPaiObj}" "${arqPaiJsObj}" "${dir3}" ;

#-------------------------------------------------------------------------------------------------------------------------------

iteration_Filho () {

  v=${1}

  for e in ${v[@]}
      do
         n=${e}   
         c=2
          . "/workspace/MirrorFashion/Filho" "${n}" "${c}" 
      done 

}

iteration_Filho "1 2 3"

 
#n=1; c=2; . "/workspace/MirrorFashion/Pai" "${c}" ;   

#-------------------------------------------------------------------------------------------------------------------------------

rmgtd2 () {

  v=${1}

  for e in ${v[@]}
      do
         n=${e}   
          cd "/workspace/MirrorFashion/src/Slide/componentsSlide/gridTD/2/gtd2f${n}"  ;
          rm -rf 'css f'
      done 

}
