#!/bin/bash

na=${1}
ta=${2}
ta2=${3}

#-------------------------------------------------------------------------------------------------------------------------------

iteration_b8 () {

  v=${1}

  for e in ${v[@]}
      do
         n=${e}   
         na="gtfh${n}"
         ta1="js"
         ta2="css"
          . "/workspace/MirrorFashion/src/Slide/componentsSlide/gridTD/1/bash/b8" "${n}" "${na}" "${ta1}" "${ta2}" 
      done 

}

#-------------------------------------------------------------------------------------------------------------------------------

#Cria um diretório chamado f(funções) contendo dois arquivos js  
#e add um dado conteudo aos dois arquivos.
#Sendo que um arquivo vai conter as funções e o outro irá realizar
#realizar testes da mesma.
CriarDirFeArqs () {

na=${1}  
contF=${2}
contFTeste=${3}
dir=${4}

echo  "Entrando no dir ${dir} ... " ;
cd "${dir}" ;

echo "Criando a pasta f ... "
mkdir f ;

echo "Entrando na pasta f ... "
cd "${dir}/f" ;

echo "Criando o arquivo ${na}F.js e ${na}FTeste.js  ... "
touch "${na}F.js" "${na}FTeste.js" ;
ls -la ;

echo "Colocando o conteudo de funções no arquivo ${na}F.js e teste em  ${na}FTeste.js ... "
echo -e "${contF}" > ${na}F.js ;
echo -e "${contFTeste}" > ${na}FTeste.js ;

echo "Exibindo o conteudo do arquivo ${na}F.js e ${na}FTeste.js ... "
cat "${na}F.js" "${na}FTeste.js" ;

echo "Executando o arquivo ${na}FTeste.js ... "
node "${na}FTeste.js" ;

}

#Cria um diretório chamado css contendo dois arquivos css  
#e add um dado conteudo aos dois arquivos. 
CriarDirCssArqs () {

na=${1}  
ta=${2}  
contCss=${3}
contCssA=${4}
dir=${5}

echo  "Entrando no dir ${dir} ... " ;
cd "${dir}" ;

echo "Criando a pasta ${ta} ... "
mkdir ${ta} ;

echo "Entrando na pasta css ... "
cd "${dir}/${ta}" ;

echo "Criando os arquivos ${na}.${ta} e ${na}A.${ta}  ... "
touch "${na}.${ta2}" "${na}A.${ta}" ;
ls -la ;

echo "Colocando o conteudo css no arquivo ${na}.${ta} ... "
echo -e "${contCss}" > ${na}.${ta} ;

echo "Colocando o conteudo da animação no arquivo ${na}A.${ta} ... "
echo -e "${contCssA}" > ${na}A.${ta} ;

echo "Exibindo o conteudo do arquivo ${na}.${ta} e ${na}A.${ta}  ... "
cat ${na}A.${ta2} ${na}.${ta2} ;

}


CriarDirCompParqs () {

na=${1}  
contCP=${2}
contCFA=${3}
dir=${4}

echo  "Entrando no dir ${dir} ... " ;
cd "${dir}" ;

echo "Criando a pasta ${na} ... "
mkdir ${na} ;

echo "Entrando na pasta ${na} ... "
cd "${dir}/${na}" ;

echo "Colocando o conteudo js no arquivo ${na}.js ... "
echo -e "${contCP}" > ${na}.${ta} ;

echo "Exibindo o conteudo do arquivo ${na}.js ... "
cat ${na}.${ta} ;

echo "Criando as pastas css e f ... "
mkdir css f;
ls -la ;

}

#Exibe o sucessor de um dado numero natural
sucessor () {

n=${1};  
n2=$[1+${n}];

echo  -e "${n2}" ;

}

#Cria um arquivo e add um conteudo
dropCont () {

cont=${1};  
arq=${2};
dir=${3};

cd "${dir}" ;
echo  -e "${cont}" > ${arq} ;

#cont="voce esta neste dir /workspace/MirrorFashion/";  arq="dropContt.txt"; dir="/workspace/MirrorFashion/"; dropCont "${cont}" "${arq}" "${dir}";
#dropCont "${cont}" "${arq}" "${dir}"
}

CriarDir () {

ndir=${1};  
dir=${2};

cd "${dir}" ;
mkdir "${ndir}" ;
ls -la | grep "${ndir}" ; 

#ndir="CriarDirteste"; dir="/workspace/MirrorFashion/"; CriarDir "${ndir}" "${dir}";
#CriarDir "${ndir}" "${dir}";
}