#!/bin/bash

n=$[${1}-1]
cont="import './css/gtfh${1}.css'

const GridTF${1} = () => {
return (
    <div className='gridTF${1} gridTF animation1_gridTF animation1_gridTF${1} gd5'>
            <div className='gridTN${1}1 gridTN${1} animation1_gridTN${1}animation1_gridTN${1}1'>
              subdestaque${n}1
            </div>
            <div className='gridTN${1}2 gridTN${1} animation1_gridTN${1}animation1_gridTN${1}2'>
              subdestaque${n}2
            </div>
            <div className='gridTN${1}3 gridTN${1} animation1_gridTN${1}animation1_gridTN${1}3'>
              subdestaque${n}3
          </div>
    </div>
    )
}

export { GridTF${1} }
"

cd "/workspace/MirrorFashion/src/Slide/componentsSlide/gridTD/1/gtf${1}" ;
echo "${cont}" > ${2}.${3} ;
cat ${2}.${3} ;