#!/bin/bash

n=$[${1}-1]    
cont="
.gridTF${1} {
background-color: wheat;
grid-area: subdestaque${n};
display: flex;
flex-direction: row;
overflow-x: scroll;
overflow-y: hidden;
height: 100vh;
}
.gridTN${1} {
position: relative;
text-align: center;
font-size: 3rem;
font-weight: 500;
min-height: 100%;
min-width: 100%;
border-radius: 25px;
}
.gridTN${1}1 {
background-color: brown;
}
.gridTN${1}2 {
background-color: tomato;
/*background-image: 
linear-gradient(
0deg,rgba(0,0,0,0.6),
rgba(0,0,0,0.2)40%,
rgba(0,0,0,0.2)80%,
rgba(0,0,0,0.4)),
url(/workspace/MirrorFashion/public/images/pink-fur-fabulous-fashion.jpg);*/
background-repeat: no-repeat;
background-size: 140%;
}
.gridTN${1}3 {
background-color: darkblue;
/*background-image: 
linear-gradient(
0deg,rgba(0,0,0,0.6),
rgba(0,0,0,0.2)40%,
rgba(0,0,0,0.2)80%,
rgba(0,0,0,0.4)),
url(/workspace/MirrorFashion/public/images/pink-fur-fabulous-fashion.jpg);*/
background-repeat: no-repeat;
background-size: 140%;
}"

cd "/workspace/MirrorFashion/src/Slide/componentsSlide/gridTD/1/gtf${1}/css" ;
echo "${cont}" > ${2}.${3} ;
cat ${2}.${3} ;