#!/bin/bash

nt=$[${1}-1]
na=${2}
ta=${3}
#-------------------------------------------------------------------------------------------------------------------------------
cont="/*#import*/
import './css/gtfh${1}.css'
import './css/gtfh${1}A.css'
import {
  Adicionar_class,
  Aumentar_ElementoPai,
  Diminuir_ElementoPai,
  gridTN,
  Analise_class
} from '../../../DBanner/f/f.js'
/*#Hook*/
const GridTF${1} = () => {
return (
    <div className='gridTF${1} gridTF animation1_gridTF animation1_gridTF${1}'
    /*onClick={gridTN.gridTN${1}.Disparar_Evento_Quando.Click}*/
    /*onMouseOut={gridTN.gridTN${1}.Disparar_Evento_Quando.Out}*/
    /*onMouseOver={gridTN.gridTN${1}.Disparar_Evento_Quando.Over}*/
    /*onDrag={gridTN.gridTN${1}.Disparar_Evento_Quando.Drag}*/
    /*onDrop={gridTN.gridTN${1}.Disparar_Evento_Quando.Drop}*/
    /*onDragStart={gridTN.gridTN${1}.Disparar_Evento_Quando.DragStart}*/
    /*onDragOver={gridTN.gridTN${1}.Disparar_Evento_Quando.DragOver*/>
            <div 
            className='gridTN${1}1 gridTN${1} animation1_gridTN${1} animation1_gridTN${1}1'
            /*onClick={gridTN.gridTN${1}.Disparar_Evento_Quando.Click}*/
            /*onMouseOut={gridTN.gridTN${1}.Disparar_Evento_Quando.Out}*/
            /*onMouseOver={gridTN.gridTN${1}.Disparar_Evento_Quando.Over}*/
            /*onDrag={gridTN.gridTN${1}.Disparar_Evento_Quando.Drag}*/
            /*onDrop={gridTN.gridTN${1}.Disparar_Evento_Quando.Drop}*/
            /*onDragStart={gridTN.gridTN${1}.Disparar_Evento_Quando.DragStart}*/
            /*onDragOver={gridTN.gridTN${1}.Disparar_Evento_Quando.DragOver*/>
              subdestaque${nt}1
            </div>
            <div className='gridTN${1}2 gridTN${1} animation1_gridTN${1} animation1_gridTN${1}2'
            /*onClick={gridTN.gridTN${1}.Disparar_Evento_Quando.Click}*/
            /*onMouseOut={gridTN.gridTN${1}.Disparar_Evento_Quando.Out}*/
            /*onMouseOver={gridTN.gridTN${1}.Disparar_Evento_Quando.Over}*/
            /*onDrag={gridTN.gridTN${1}.Disparar_Evento_Quando.Drag}*/
            /*onDrop={gridTN.gridTN${1}.Disparar_Evento_Quando.Drop}*/
            /*onDragStart={gridTN.gridTN${1}.Disparar_Evento_Quando.DragStart}*/
            /*onDragOver={gridTN.gridTN${1}.Disparar_Evento_Quando.DragOver*/>
              subdestaque${nt}2
            </div>
            <div className='gridTN${1}3 gridTN${1} animation1_gridTN${1} animation1_gridTN${1}3'
            /*onClick={gridTN.gridTN${1}.Disparar_Evento_Quando.Click}*/
            /*onMouseOut={gridTN.gridTN${1}.Disparar_Evento_Quando.Out}*/
            /*onMouseOver={gridTN.gridTN${1}.Disparar_Evento_Quando.Over}*/
            /*onDrag={gridTN.gridTN${1}.Disparar_Evento_Quando.Drag}*/
            /*onDrop={gridTN.gridTN${1}.Disparar_Evento_Quando.Drop}*/
            /*onDragStart={gridTN.gridTN${1}.Disparar_Evento_Quando.DragStart}*/
            /*onDragOver={gridTN.gridTN${1}.Disparar_Evento_Quando.DragOver*/>
              subdestaque${nt}3
          </div>
    </div>
    )
}
/*#Export*/
export { GridTF${1} }
"
#-------------------------------------------------------------------------------------------------------------------------------
cont2=" /*!*/

.for_posiçao2_of_gridTF${1} {
    animation-name: for_posiçao2_of_gridTF${1};
    animation-duration: 1s;
    animation-iteration-count: 1;
  
    z-index: 2;
    height: 120%;
    width: 130%;
    left: 0;
    top: -5vh; 
    rotate: 0deg;
  }
  
  .for_posiçao1_of_gridTF${1} {
    animation-name: for_posiçao1_of_gridTF${1};
    animation-duration: 1s;
    animation-iteration-count: 1;
  
    z-index: 1;
    height: 100%;
    width: 100%;
    left: -40vw;
    top: 0vh; 
  }
  
  @keyframes for_posiçao2_of_gridTF${1} {
    0% {
      z-index: 1;
      height: 100%;
      width: 100%;    
      left: -40vw;
    }
    25% {
      left: -80vw;
      top: 10vh;
      z-index: 2
    }
    50% {
      top: 20vh;
      z-index: 2;
      rotate: 20deg;
    }
    75% {
      z-index: 2;
      height: 120%;
      width: 130%;    
      left: 0;
      top: -20vh;
      rotate: -20deg;
    }
    100% {
      z-index: 2;
      height: 120%;
      width: 130%;
      left: 0;
      top: -5vh;
      rotate: 0deg;
    }
  }
  
  @keyframes for_posiçao1_of_gridTF${1} {
    0% {
     z-index: 2;
      height: 110%;
      width: 120%;
      left: 0;
      top: 0;
    }
    25% {
      z-index: 1;
      left: 40vw;
      top: -10vh;
    }
    50% {
     top: -20vh;
    }
    75% {
      z-index: 1;
      height: 100%;
      width: 100%;
      left: -40vw;
      top: 10vh;
    }
    100% {
      z-index: 1;
      height: 100%;
      width: 100%;
      left: -40vw;
      top: 0vh;
    }
  }
  /*!*/ "
#-------------------------------------------------------------------------------------------------------------------------------
  cont3="/*#Comentários*/
  //Funções gtf${1}
  /*#Obj_Main*/  
  const gtf${1}_funções = {
    /*#f1*/
    teste : () => {
        console.log('Esse é o objeto que contém métodos do hook gtf${1}')
    }
  }
  /*#Export*/
  export { gtf${1}_funções }
  " 
#-------------------------------------------------------------------------------------------------------------------------------
echo  "Entrando no dir /workspace/MirrorFashion/src/Slide/componentsSlide/gridTD/1/ ... " ;
cd "/workspace/MirrorFashion/src/Slide/componentsSlide/gridTD/1/" ;

echo "Criando a pasta gtf${1} ... "
mkdir gtf${1} ;
#-------------------------------------------------------------------------------------------------------------------------------
echo "Entrando na pasta gtf${1} ... "
cd "/workspace/MirrorFashion/src/Slide/componentsSlide/gridTD/1/gtf${1}" ;

echo "Colocando o conteudo js no arquivo gtfh${1}.js ... "
echo -e "${cont}" > ${na}.${ta} ;

echo "Exibindo o conteudo do arquivo gtfh${1}.js ... "
cat ${na}.$ta ;

echo "Criando as pastas css e f ... "
mkdir css f;
ls -la ;
#-------------------------------------------------------------------------------------------------------------------------------
echo "Entrando na pasta css ... "
cd "/workspace/MirrorFashion/src/Slide/componentsSlide/gridTD/1/gtf${1}/css" ;

echo "Criando os arquivos gtfh${1}.css e gtfh${1}A.css  ... "
touch "gtfh${1}.css" "gtfh${1}A.css" ;
ls -la ;

echo "Colocando o conteudo da animação no arquivo gtfh${1}A.css ... "
echo -e "${cont2}" > gtfh${1}A.css ;

echo "Exibindo o conteudo do arquivo gtfh${1}A.css ... "
cat gtfh${1}A.css ;
#-------------------------------------------------------------------------------------------------------------------------------
echo "Entrando na pasta f ... "
cd "/workspace/MirrorFashion/src/Slide/componentsSlide/gridTD/1/gtf${1}/f" ;

echo "Criando o arquivo gtfhF${1}.js  ... "
touch "gtfhF${1}.js" ;
ls -la ;

echo "Colocando o conteudo de funções no arquivo gtfhF${1}.js ... "
echo -e "${cont3}" > gtfhF${1}.js ;

echo "Exibindo o conteudo do arquivo gtfhF${1}.js ... "
cat gtfhF${1}.js ;
